#include "particle_system/common.h"
#include "utils.h"

layout(binding = 0) buffer PS_Data
{
    ParticleSystemData g_Data;
};

layout(binding = 1) buffer PackedParticles
{
    PackedParticle g_Particles[];
};

layout(binding = 2) readonly buffer Emitters
{
    Emitter g_Emitters[];
};

layout(binding = 3) buffer DeadIndices
{
    uint g_DeadIndices[];
};

layout(binding = 4) buffer AliveIndicesPreSim
{
    uint g_AliveIndicesPreSim[];
};

layout(binding = 5) readonly buffer EmittersSpawnCountBuffer
{
    uint g_EmittersSpawnCount[];
};

layout(binding = 6) readonly buffer TransformsBuffer
{
    mat4 g_Transforms[];
};

layout(binding = 7) readonly buffer MeshVerticesBuffer
{
    MeshVertex g_Vertices[];
};

layout(binding = 8) readonly buffer MeshIndicesBuffer
{
    uint g_Indices[];
};

layout(push_constant) uniform PushConstants
{
    uint g_PreSimIndex;
    uint g_FrameNumber;
    uint g_NumEmitters;
    uint g_MaxParticles;
};

void PushAlive(uint particleIndex)
{
    uint insertIdx;
    EG_SUBGROUP_ATOMIC_INCREMENT(g_Data.AliveCount[g_PreSimIndex], true, insertIdx);
    g_AliveIndicesPreSim[insertIdx] = particleIndex;
}

// Returns false if there are no slots available
bool PopDead(out uint particleIndex)
{
    uint index, origDeadCount;
    EG_SUBGROUP_ATOMIC_DECREMENT(g_Data.DeadCount, true, index, origDeadCount);
    if (index == 0 || index > origDeadCount || origDeadCount > g_MaxParticles) // `origDeadCount > g_MaxParticles` - Someone overflowed, which means there are no slots available
    {
        // Overflow, ignore particle emission
        EG_SUBGROUP_ATOMIC_INCREMENT(g_Data.DeadCount, true, index);
        return false;
    }
    particleIndex = g_DeadIndices[index - 1];
    return true;
}

uint GetEmitterIndex(uint id)
{
    for (uint i = 0; i < g_NumEmitters; ++i)
    {
        if (id < g_EmittersSpawnCount[i])
            return i;
        id -= g_EmittersSpawnCount[i];
    }
}

void GetPosAndNormalOnMesh(Emitter emitter, inout Random random, inout vec3 pos, inout vec3 normal)
{
    // random triangle on emitter surface
	const uint triangleCount = emitter.IndexCount / 3;
	const uint tri = Random_NextUint(random, triangleCount);

	// load indices of triangle from index buffer
	uint i0 = g_Indices[emitter.IndexOffset + tri * 3 + 0];
	uint i1 = g_Indices[emitter.IndexOffset + tri * 3 + 1];
	uint i2 = g_Indices[emitter.IndexOffset + tri * 3 + 2];

	// load vertices of triangle from vertex buffer
    MeshVertex v0 = g_Vertices[emitter.VertexOffset + i0];
    MeshVertex v1 = g_Vertices[emitter.VertexOffset + i1];
    MeshVertex v2 = g_Vertices[emitter.VertexOffset + i2];

    // random barycentric coords
    vec2 buv = Random_NextFloat2(random);
	if (buv.x + buv.y > 1.f)
	{
		buv.x = 1.f - buv.x;
		buv.y = 1.f - buv.y;
	}
	
    // compute final surface position on triangle from barycentric coords:
	pos = BarycentricInterp(v0.Position, v1.Position, v2.Position, buv);
	normal = normalize(BarycentricInterp(Particle_UnpackNormal(v0.Normal), Particle_UnpackNormal(v1.Normal), Particle_UnpackNormal(v2.Normal), buv));
}

void Emitter_GetParticlePositionAndNormal(Emitter emitter, inout Random random, out vec3 position, out vec3 normal)
{
	position = vec3(0);
	normal = vec3(0);
	switch (emitter.EmissionShape)
	{
		// case EmissionShapeType_Point: return; // Returns 0
		case EmissionShapeType_Sphere:
			position = Random_PointInSphere(random, emitter.SphereRadius);
            normal = normalize(position);
			break;
		case EmissionShapeType_SphereSurface:
			position = Random_PointOnSphere(random, emitter.SphereRadius);
            normal = normalize(position);
			break;
		case EmissionShapeType_Box:
			position = mix(emitter.BoxMin, emitter.BoxMax, Random_NextFloat3(random));
			break;
		case EmissionShapeType_Ring:
			position = Random_PointInRing(random, emitter.RingRadius, emitter.RingThickness);
			break;
		case EmissionShapeType_Mesh:
			GetPosAndNormalOnMesh(emitter, random, position, normal);
			break;
	}
}

layout(local_size_x = EG_PS_THREAD_SIZE, local_size_y = 1, local_size_z = 1) in;

void main()
{
    const uint gidx = gl_GlobalInvocationID.x;
    if (gidx >= g_Data.EmitCount)
        return;

    uint particleIndex;
    if (!PopDead(particleIndex))
        return;

    const uint emitterIndex = GetEmitterIndex(gidx);
    const Emitter emitter = g_Emitters[emitterIndex];

    Random random = Random_Init(uvec2(0, gidx), g_FrameNumber);

    const mat4 worldTr = g_Transforms[emitter.TransformIndex];

    vec3 position, normal;
    Emitter_GetParticlePositionAndNormal(emitter, random, position, normal);
    position = vec3(worldTr * vec4(position, 1.f));
    if (NOT_ZERO(normal) && emitter.NormalVelocityFactor != 0.f)
    {
        const mat3 normalModel = mat3(transpose(inverse(worldTr)));
        normal = normalize(normalModel * normal);
    }

    const float bounciness = mix(emitter.BouncinessMin, emitter.BouncinessMax, Random_NextFloat(random));
    const float opacity = emitter.ColorStart.a;

    Particle particle;
    particle.Size = emitter.SizeStart.xy;
    particle.CurrentLifetime = 0.f;
    particle.Lifetime = mix(emitter.LifetimeMin, emitter.LifetimeMax, Random_NextFloat(random));

    particle.Position = position;
    particle.Flags = EmitterFlagsToParticleFlags(emitter.Flags);

    particle.Velocity = normal * emitter.NormalVelocityFactor + mix(emitter.VelocityMin, emitter.VelocityMax, Random_NextFloat3(random));
    particle.Bounciness = float16_t(bounciness);
    particle.RotationZ = float16_t(emitter.RotationZStart);

    particle.VelocityCoef = emitter.VelocityCoefStart;
    particle.EmitterIndex = emitterIndex;

    particle.Color = f16vec4(emitter.ColorStart);
    particle.TextureIndex = emitter.TextureIndex;
    particle.AnimationSpriteCoord = u16vec2(0);
    particle.AnimationLerp = float16_t(0.f);

    g_Particles[particleIndex] = Particle_Pack(particle, u16vec2(emitter.AnimationImagesNum));
    PushAlive(particleIndex);
}
