#include "particle_system/common.h"
#include "utils.h"

layout(binding = 0) buffer PS_Data
{
    ParticleSystemData g_Data;
};

layout(binding = 1) buffer PackedParticles
{
    PackedParticle g_Particles[];
};

layout(binding = 2) readonly buffer Emitters
{
    Emitter g_Emitters[];
};

layout(binding = 3) buffer DeadIndices
{
    uint g_DeadIndices[];
};

layout(binding = 4) buffer AliveIndicesPreSim
{
    uint g_AliveIndicesPreSim[];
};

layout(binding = 5) buffer AliveIndicesPostSim
{
    uint g_AliveIndicesPostSim[];
};

layout(binding = 6) buffer IndicesToRenderTranslucentBuffer
{
    uint g_IndicesToRenderTranslucent[];
};

layout(binding = 7) buffer DistancesTranslucentBuffer
{
    float g_DistancesTranslucent[];
};

layout(binding = 8) buffer DrawArgsBuffer
{
    DrawArgs g_DrawArgs[2];
};

layout(binding = 9)  uniform sampler2D g_Depth;
layout(binding = 10) uniform sampler2D g_Normal;

layout(binding = 11) uniform CameraView
{
	mat4 g_CameraView;
};

layout(binding = 12) buffer IndicesToRenderOpaqueBuffer
{
    uint g_IndicesToRenderOpaque[];
};

#ifdef EG_SORT_OPAQUE
layout(binding = 13) buffer DistancesOpaqueBuffer
{
    float g_DistancesOpaque[];
};
#endif

layout(push_constant) uniform PushConstants
{
    mat4 g_ViewProj;

    vec3 g_Gravity;
    float g_CameraNear;

    float g_CameraFar;
    float g_DeltaTime;
    uint g_PreSimIndex;
    uint g_PostSimIndex;
    uint g_MaxParticles;
};

void PushAlive(uint particleIndex)
{
    uint insertIdx;
    EG_SUBGROUP_ATOMIC_INCREMENT(g_Data.AliveCount[g_PostSimIndex], true, insertIdx);
    g_AliveIndicesPostSim[insertIdx] = particleIndex;
}

// Returns false if there are no slots available
bool PopAlive(out uint particleIndex)
{
    uint index, origAliveCount;
    EG_SUBGROUP_ATOMIC_DECREMENT(g_Data.AliveCount[g_PreSimIndex], true, index, origAliveCount);
    if (index == 0 || index > origAliveCount || origAliveCount > g_MaxParticles) // `origAliveCount > g_MaxParticles` - Someone overflowed, which means there are no slots available
    {
        // Overflow, ignore particle emission
        EG_SUBGROUP_ATOMIC_INCREMENT(g_Data.AliveCount[g_PreSimIndex], true, index);
        return false;
    }
    particleIndex = g_AliveIndicesPreSim[index - 1];
    return true;
}

void PushDead(uint particleIndex)
{
    uint insertIdx;
    EG_SUBGROUP_ATOMIC_INCREMENT(g_Data.DeadCount, true, insertIdx);
    g_DeadIndices[insertIdx] = particleIndex;
}

void PushToDrawOpaque(uint particleIndex, float dist)
{
    uint insertIdx;
    EG_SUBGROUP_ATOMIC_INCREMENT(g_DrawArgs[0].InstanceCount, true, insertIdx);
    g_IndicesToRenderOpaque[insertIdx] = particleIndex;
#ifdef EG_SORT_OPAQUE
    g_DistancesOpaque[insertIdx] = dist;
#endif
}

void PushToDrawTranslucent(uint particleIndex, float dist)
{
    uint insertIdx;
    EG_SUBGROUP_ATOMIC_INCREMENT(g_DrawArgs[1].InstanceCount, true, insertIdx);
    g_IndicesToRenderTranslucent[insertIdx] = particleIndex;
    g_DistancesTranslucent[insertIdx] = dist;
}

layout(local_size_x = EG_PS_THREAD_SIZE, local_size_y = 1, local_size_z = 1) in;

void main()
{
    const uint gidx = gl_GlobalInvocationID.x;
    if (gidx >= g_Data.SimulateCount)
        return;

    uint particleIndex;
    if (!PopAlive(particleIndex))
        return;

    Particle particle = Particle_Unpack(g_Particles[particleIndex]);
    if (particle.CurrentLifetime >= particle.Lifetime)
    {
        PushDead(particleIndex);
        return;
    }

    vec3 force = vec3(0.f);
    const Emitter emitter = g_Emitters[particle.EmitterIndex];
    if (HasFlag(emitter.Flags, Emitter_ApplyGravity_Mask))
        force += g_Gravity;
        
    // Apply radial & tangential accelerations
    {
        vec3 dir = particle.Position - emitter.WorldPos;
        if (dot(dir, dir) > 0.0001f) // if dir is not zero
        {
            dir = normalize(dir);
            force += dir * emitter.RadialAcceleration; // Radial
            force += vec3(-dir.y, dir.x, 0.f) * emitter.TangentialAcceleration; // Tangential
        }
    }
    particle.Velocity += force * g_DeltaTime;

    if (emitter.CollisionType != ParticleCollisionType_None)
    {
        vec4 position = g_ViewProj * vec4(particle.Position, 1.0);
        position.xyz /= position.w;

        const vec2 uv = position.xy * 0.5 + vec2(0.5);
        if (uv.x >= 0.f && uv.y >= 0.f && uv.x <= 1.f && uv.y <= 1.f)
        {
            const vec3 normal = DecodeNormal(texture(g_Normal, uv).xy); // .xy - Geometry Normal
            const float depth = ToLinear(texture(g_Depth, uv).x, g_CameraNear, g_CameraFar);
            const vec2 particleSize = particle.Size * emitter.ColliderSizeRatio.xy;
            const float particleSizeMax = max(particleSize.x, particleSize.y);
		    const float surfaceThickness = 1.5f;
		    if ((position.w + particleSizeMax > depth) && (position.w - particleSizeMax < depth + surfaceThickness))
            {
                if (dot(particle.Velocity, normal) < 0.0)
                {
                    switch (emitter.CollisionType)
                    {
                        case ParticleCollisionType_DestroyOnHit:
                            PushDead(particleIndex);
                            return;
                        case ParticleCollisionType_Bounce:
                            particle.Velocity = reflect(particle.Velocity, normal) * particle.Bounciness; 
                            break;
                    }
                }
            }
        }
    }

    // Handle animation
    float animationLerp = 0.f;
    if (emitter.TextureIndex != EG_INVALID_INDEX)
    {
        const float nextLifetime = particle.CurrentLifetime + g_DeltaTime;
        const float animationFPS = emitter.AnimationSpeed * float(emitter.AnimationImagesNum.x * emitter.AnimationImagesNum.y) / particle.Lifetime;
        const float lifetimeMod = particle.Lifetime - uint(particle.Lifetime / animationFPS) * animationFPS;
        animationLerp = lifetimeMod / animationFPS;

        // Don't update anim if about to die
        uint AdvanceAnimationCount = nextLifetime >= particle.Lifetime ? 0u : uint(nextLifetime * animationFPS) - uint(particle.CurrentLifetime * animationFPS);
        while (AdvanceAnimationCount > 0) // TODO: Advance at once
        {
            Particle_AdvanceAnimation(particle.AnimationSpriteCoord, u16vec2(emitter.AnimationImagesNum));
            --AdvanceAnimationCount;
        }
    }

    const float lifeAlpha = particle.CurrentLifetime / particle.Lifetime;
    const float rotationZ = mix(emitter.RotationZStart, emitter.RotationZEnd, lifeAlpha);

    particle.Size = mix(emitter.SizeStart.xy, emitter.SizeEnd.xy, lifeAlpha);
    particle.CurrentLifetime += g_DeltaTime;
    particle.Position += particle.Velocity * particle.VelocityCoef * g_DeltaTime;
    particle.Flags = EmitterFlagsToParticleFlags(emitter.Flags);
    particle.RotationZ = float16_t(rotationZ);
    particle.VelocityCoef = mix(emitter.VelocityCoefStart, emitter.VelocityCoefEnd, lifeAlpha);
    particle.Color = f16vec4(mix(emitter.ColorStart, emitter.ColorEnd, lifeAlpha));
    particle.TextureIndex = emitter.TextureIndex;
    particle.AnimationLerp = float16_t(animationLerp);

    g_Particles[particleIndex] = Particle_Pack(particle, u16vec2(emitter.AnimationImagesNum));
    PushAlive(particleIndex);

    if (emitter.IsVisible == 1)
    {
        const vec4 viewPos = g_CameraView * vec4(particle.Position, 1.0);
        if (HasFlag(emitter.Flags, Emitter_AlphaBlending_Mask))
            PushToDrawTranslucent(particleIndex, viewPos.z);
        else
            PushToDrawOpaque(particleIndex, viewPos.z);
    }
}
