#include "defines.h"
#include "utils.h"

#extension GL_KHR_shader_subgroup_basic : require
#extension GL_KHR_shader_subgroup_ballot : require
#extension GL_KHR_shader_subgroup_shuffle : require

#include "screen_space_reflections/common.h"
#include "screen_space_reflections/ffx_denoiser_reflections_common.h"

layout(binding = 1, r16f) uniform readonly image2D g_VarianceHistory;
layout(binding = 2, r32ui) uniform coherent uimageBuffer g_RayCounter;
layout(binding = 3, r32ui) uniform coherent uimageBuffer g_DenoiserTileList;
layout(binding = 4) buffer RayList
{
	uint g_RayList[];
};
layout(binding = 5) uniform sampler2D g_Depth;
layout(binding = 6) uniform sampler2D g_Normal;
layout(binding = 7) uniform sampler2D g_AlbedoRoughness;
layout(binding = 8, rgba16f) uniform writeonly image2D g_IntersectionOutput;
layout(binding = 9, r8) uniform writeonly image2D g_ExtractedRoughness;

shared uint g_TileCount;

layout(push_constant) uniform PushConstants
{
    uvec2 g_Size;
    vec2 g_TexelSize;
    uint g_SamplesPerQuad;
};

const float g_TemporalVarianceThreshold = 0.f;

void IncrementRayCounter(uint value, out uint originalValue)
{
    originalValue = imageAtomicAdd(g_RayCounter, 0, value);
}

void IncrementDenoiserTileCounter(out uint originalValue)
{
    originalValue = imageAtomicAdd(g_RayCounter, 2, 1);
}

void StoreRay(uint index, uvec2 rayCoord, bool copyHorizontal, bool copyVertical, bool copyDiagonal)
{
    g_RayList[index] = PackRayCoords(rayCoord, copyHorizontal, copyVertical, copyDiagonal); // Store out pixel to trace
}

void StoreDenoiserTile(uint index, uvec2 tileCoord)
{
    imageStore(g_DenoiserTileList, int(index), uvec4(((tileCoord.y & 0xFFFFu) << 16) | ((tileCoord.x & 0xFFFFu) << 0))); // Store out pixel to trace
}

bool IsReflectiveSurface(uvec2 pixelCoordinate, float roughness)
{
    return texelFetch(g_Depth, ivec2(pixelCoordinate), 0).x < EG_DEPTH_FAR;
}

bool IsBaseRay(uvec2 dispatchThreadId, uint samplesPerQuad)
{
    switch (samplesPerQuad) {
    case 1:
        return ((dispatchThreadId.x & 1) | (dispatchThreadId.y & 1)) == 0; // Deactivates 3 out of 4 rays
    case 2:
        return (dispatchThreadId.x & 1) == (dispatchThreadId.y & 1); // Deactivates 2 out of 4 rays. Keeps diagonal.
    default: // case 4:
        return true;
    }
}

vec3 SampleEnvironmentMap(uvec2 dispatchThreadId, float roughness)
{
    return vec3(0);
}

void ClassifyTiles(uvec2 dispatchThreadId, uvec2 groupThreadId, float roughness)
{
    g_TileCount = 0;

    bool bFirstWaveLane = subgroupElect();

    // First we figure out on a per thread basis if we need to shoot a reflection ray.
    // Disable offscreen pixels
    bool bNeedsRay = !(dispatchThreadId.x >= g_Size.x || dispatchThreadId.y >= g_Size.y);

    // Dont shoot a ray on very rough surfaces.
    bool bReflectiveSurface = IsReflectiveSurface(dispatchThreadId, roughness);
    bool bGlossyReflection = FFX_DNSR_Reflections_IsGlossyReflection(roughness);
    bNeedsRay = bNeedsRay && bGlossyReflection && bReflectiveSurface;

    // Also we dont need to run the denoiser on mirror reflections.
    bool bNeedsDenoiser = bNeedsRay && !FFX_DNSR_Reflections_IsMirrorReflection(roughness);

    // Decide which ray to keep
    bool bBaseRay = IsBaseRay(dispatchThreadId, g_SamplesPerQuad);
    bNeedsRay = bNeedsRay && (!bNeedsDenoiser || bBaseRay); // Make sure to not deactivate mirror reflection rays.

    if (bNeedsDenoiser && !bNeedsRay)
    {
        bool bHasTemporalVariance = imageLoad(g_VarianceHistory, ivec2(dispatchThreadId)).x > g_TemporalVarianceThreshold;
        bNeedsRay = bNeedsRay || bHasTemporalVariance;
    }

    groupMemoryBarrier();
    barrier();

    // Now we know for each thread if it needs to shoot a ray and wether or not a denoiser pass has to run on this pixel.

    if (bGlossyReflection && bReflectiveSurface)
        atomicAdd(g_TileCount, 1);

    // Next we have to figure out for which pixels that ray is creating the values for. Thus, if we have to copy its value horizontal, vertical or across.
    bool bRequireCopy = !bNeedsRay && bNeedsDenoiser; // Our pixel only requires a copy if we want to run a denoiser on it but don't want to shoot a ray for it.
    bool bCopyHorizontal = (g_SamplesPerQuad != 4) && bBaseRay && subgroupShuffle(bRequireCopy, gl_SubgroupInvocationID ^ 1); // QuadReadAcrossX
    bool bCopyVertical = (g_SamplesPerQuad == 1) && bBaseRay && subgroupShuffle(bRequireCopy, gl_SubgroupInvocationID ^ 2); // QuadReadAcrossY
    bool bCopyDiagonal = (g_SamplesPerQuad == 1) && bBaseRay && subgroupShuffle(bRequireCopy, gl_SubgroupInvocationID ^ 3); // QuadReadAcrossDiagonal

    // Thus, we need to compact the rays and append them all at once to the ray list.
    uvec4 mask = subgroupBallot(bNeedsRay);
    uint localRayIndexInWave = subgroupBallotExclusiveBitCount(mask);
    uint waveRayCount = subgroupBallotBitCount(mask);
    uint baseRayIndex;
    if (bFirstWaveLane)
    {
        IncrementRayCounter(waveRayCount, baseRayIndex);
    }
    baseRayIndex = subgroupBroadcastFirst(baseRayIndex);
    if (bNeedsRay)
    {
        uint rayIndex = baseRayIndex + localRayIndexInWave;
        StoreRay(rayIndex, dispatchThreadId, bCopyHorizontal, bCopyVertical, bCopyDiagonal);
    }

    vec4 intersectionOutput = vec4(0);
    if (bReflectiveSurface && !bGlossyReflection)
    {
        // Fall back to environment map without preparing a ray
        intersectionOutput.xyz = SampleEnvironmentMap(dispatchThreadId, roughness);
    }
    imageStore(g_IntersectionOutput, ivec2(dispatchThreadId), intersectionOutput);

    groupMemoryBarrier();
    barrier();

    if (groupThreadId.x == 0 && groupThreadId.y == 0 && g_TileCount > 0)
    {
        uint tileOffset;
        IncrementDenoiserTileCounter(tileOffset);
        StoreDenoiserTile(tileOffset, dispatchThreadId.xy);
    }
}

#define GROUP_SIZE 8
layout(local_size_x = GROUP_SIZE, local_size_y = GROUP_SIZE) in;

void main()
{
    const uvec2 groupId = uvec2(gl_WorkGroupID);
    const uint groupIndex = gl_LocalInvocationIndex;

    const uvec2 groupThreadId = FFX_DNSR_Reflections_RemapLane8x8(groupIndex); // Remap lanes to ensure four neighboring lanes are arranged in a quad pattern
    const uvec2 dispatchThreadId = groupId * 8 + groupThreadId;

    float roughness = texelFetch(g_AlbedoRoughness, ivec2(dispatchThreadId), 0).w;
    roughness = roughness * roughness;

    ClassifyTiles(dispatchThreadId, groupThreadId, roughness);

    // Extract only the channel containing the roughness to avoid loading all 4 channels in the follow up passes.
    imageStore(g_ExtractedRoughness, ivec2(dispatchThreadId), vec4(roughness));
}
