#include "defines.h"
#include "utils.h"

layout(binding = 0, rgba16f) uniform readonly image2D g_ReflectionTarget;
layout(binding = 1) uniform sampler2D g_Normals;
layout(binding = 2) uniform sampler2D g_Albedo;
layout(binding = 3) uniform sampler2D g_MaterialData;
layout(binding = 4) uniform sampler2D g_BRDF;
layout(binding = 5, r11f_g11f_b10f) uniform image2D g_Result;

layout(push_constant) uniform PushConstants
{
    uvec2 g_Size;
    vec2 g_TexelSize;
    vec3 g_CameraDir;
};

// Important bits from the PBR shader
vec3 getIBLContribution(float perceptualRoughness, vec3 specularColor, vec3 specularLight, vec3 n)
{
    float NdotV = clamp(dot(n, g_CameraDir), 0.0, 1.0);
    vec2 brdfSamplePoint = clamp(vec2(NdotV, perceptualRoughness), vec2(0.0, 0.0), vec2(1.0, 1.0));
    // retrieve a scale and bias to F0. See [1], Figure 3
    vec2 brdf = texture(g_BRDF, brdfSamplePoint).rg;

    vec3 specular = specularLight * (specularColor * brdf.x + brdf.y); 
    return specular;
}

#define GROUP_SIZE 8
layout(local_size_x = GROUP_SIZE, local_size_y = GROUP_SIZE) in;

void main()
{
    const ivec2 pixelCoords = ivec2(gl_GlobalInvocationID);
    if (pixelCoords.x >= g_Size.x || pixelCoords.y >= g_Size.y)
        return;

    const vec2 uv = (pixelCoords + 0.5) * g_TexelSize;
     
    vec3 radiance = imageLoad(g_ReflectionTarget, pixelCoords).rgb;
    const vec3 albedo = texture(g_Albedo, uv).rgb;
    const vec2 materialData = texture(g_MaterialData, uv).xz;
    const float metalness = materialData.x;
    const float roughness = materialData.y;

    vec3 F0 = vec3(EG_BASE_REFLECTIVITY);
    vec3 specularColor = mix(F0, albedo, metalness);
    float perceptualRoughness = roughness;
    vec3 normal = DecodeNormal(texture(g_Normals, uv).zw);

    uint showReflectionTarget = 0;
    uint drawReflections = 1;

    if (showReflectionTarget == 1)
    {
        imageStore(g_Result, pixelCoords, vec4(radiance, 0));
    }
    else if (drawReflections == 1)
    {
        vec3 destinationColor = imageLoad(g_Result, pixelCoords).rgb;
        radiance = getIBLContribution(perceptualRoughness, specularColor, radiance, normal);
        imageStore(g_Result, pixelCoords, vec4(destinationColor + 2.0 * radiance, 1)); // Show the reflections applied to the scene
    }
}
