#include "defines.h"
#include "utils.h"
#include "screen_space_reflections/common.h"

layout(binding = 1) uniform sampler2D g_Radiance;
layout(binding = 2) uniform sampler2D g_Variance;
layout(binding = 3) uniform sampler2D g_AverageRadiance;
layout(binding = 4) uniform sampler2D g_Roughness;
layout(binding = 5) uniform sampler2D g_Normal;
layout(binding = 6) uniform sampler2D g_Depth;
layout(binding = 7, r32ui) uniform uimageBuffer g_DenoiserTileList;

layout(binding = 8, rgba16f) uniform writeonly image2D g_OutRadiance;
layout(binding = 9, r16f) uniform writeonly image2D g_OutVariance;

layout(push_constant) uniform PushConstants
{
    uvec2 g_Size;
    vec2 g_TexelSize;
};

f16vec3 FFX_DNSR_Reflections_SampleAverageRadiance(vec2 uv)
{
    return f16vec3(texture(g_AverageRadiance, uv).xyz);
}

float16_t FFX_DNSR_Reflections_LoadRoughness(ivec2 pixelCoordinate)
{
    return float16_t(texelFetch(g_Roughness, pixelCoordinate, 0).x);
}

void FFX_DNSR_Reflections_LoadNeighborhood(ivec2 pixelCoordinate, out f16vec3 radiance, out float16_t variance, out f16vec3 normal, out float depth, ivec2 screen_size)
{
    radiance = f16vec3(texelFetch(g_Radiance, pixelCoordinate, 0).xyz);
    variance = float16_t(texelFetch(g_Variance, pixelCoordinate, 0).x);

    normal = f16vec3(DecodeNormal(texelFetch(g_Normal, pixelCoordinate, 0).zw)); // zw - is a shading normal;

    vec2 uv = (pixelCoordinate.xy + 0.5f) * g_TexelSize;
    depth = FFX_DNSR_Reflections_GetLinearDepth(uv, texelFetch(g_Depth, pixelCoordinate, 0).x);
}

void FFX_DNSR_Reflections_StorePrefilteredReflections(ivec2 pixelCoordinate, f16vec3 radiance, float16_t variance)
{
    imageStore(g_OutRadiance, pixelCoordinate, radiance.xyzz);
    imageStore(g_OutVariance, pixelCoordinate, vec4(variance.x));
}

#include "screen_space_reflections/ffx_denoiser_reflections_prefilter.h"

#define GROUP_SIZE 8
layout(local_size_x = GROUP_SIZE, local_size_y = GROUP_SIZE) in;

void main()
{
    const ivec2 groupThreadId = ivec2(gl_LocalInvocationID);
    const uint  groupIndex    = gl_LocalInvocationIndex;
    const uint  groupId       = uint(gl_WorkGroupID);

    const uint  packedCoords             = imageLoad(g_DenoiserTileList, int(groupId)).x;
    const ivec2 dispatchThreadId         = ivec2(packedCoords & 0xffffu, (packedCoords >> 16) & 0xffffu) + groupThreadId;
    const ivec2 dispatchGroupId          = dispatchThreadId / 8;
    const uvec2 remappedGroupThreadId    = FFX_DNSR_Reflections_RemapLane8x8(groupIndex);
    const uvec2 remappedDispatchThreadId = dispatchGroupId * 8 + remappedGroupThreadId;

    FFX_DNSR_Reflections_Prefilter(ivec2(remappedDispatchThreadId), ivec2(remappedGroupThreadId), g_Size);
}
