#extension GL_EXT_shader_explicit_arithmetic_types_float16 : require
#extension GL_EXT_shader_explicit_arithmetic_types_int16 : require

#include "defines.h"
#include "screen_space_reflections/common.h"

layout(binding = 1) uniform sampler2D g_AverageRadiance;
layout(binding = 2) uniform sampler2D g_ReprojectedRadiance;
layout(binding = 3) uniform sampler2D g_Radiance;
layout(binding = 4) uniform sampler2D g_Roughness;
layout(binding = 5) uniform sampler2D g_Variance;
layout(binding = 6) uniform sampler2D g_SampleCount;
layout(binding = 7, r32ui) uniform uimageBuffer g_DenoiserTileList;

layout(binding = 8, rgba16f) uniform writeonly image2D g_OutRadiance;
layout(binding = 9, r16f) uniform writeonly image2D g_OutVariance;

layout(push_constant) uniform PushConstants
{
    uvec2 g_Size;
    vec2 g_TexelSize;
};

const float g_TemporalStabilityFactor = 0.7;

f16vec3 FFX_DNSR_Reflections_SampleAverageRadiance(vec2 uv)
{
    return f16vec3(texture(g_AverageRadiance, uv).xyz);
}

f16vec3 FFX_DNSR_Reflections_LoadRadiance(ivec2 pixelCoordinate)
{
    return f16vec3(texelFetch(g_Radiance, pixelCoordinate, 0).xyz);
}

f16vec3 FFX_DNSR_Reflections_LoadRadianceReprojected(ivec2 pixelCoordinate)
{
    return f16vec3(texelFetch(g_ReprojectedRadiance, pixelCoordinate, 0).xyz);
}

float16_t FFX_DNSR_Reflections_LoadRoughness(ivec2 pixelCoordinate)
{
    return float16_t(texelFetch(g_Roughness, pixelCoordinate, 0).x);
}

float16_t FFX_DNSR_Reflections_LoadVariance(ivec2 pixelCoordinate)
{
    return float16_t(texelFetch(g_Variance, pixelCoordinate, 0).x);
}

float16_t FFX_DNSR_Reflections_LoadNumSamples(ivec2 pixelCoordinate)
{
    return float16_t(texelFetch(g_SampleCount, pixelCoordinate, 0).x);
}

void FFX_DNSR_Reflections_StoreTemporalAccumulation(ivec2 pixelCoordinate, f16vec3 radiance, float16_t variance)
{
    imageStore(g_OutRadiance, pixelCoordinate, radiance.xyzz);
    imageStore(g_OutVariance, pixelCoordinate, vec4(variance.x));
}

#include "screen_space_reflections/ffx_denoiser_reflections_resolve_temporal.h"

#define GROUP_SIZE 8
layout(local_size_x = GROUP_SIZE, local_size_y = GROUP_SIZE) in;

void main()
{
    const ivec2 groupThreadId = ivec2(gl_LocalInvocationID);
    const uint  groupIndex    = gl_LocalInvocationIndex;
    const uint  groupId       = uint(gl_WorkGroupID);

    const uint  packedCoords             = imageLoad(g_DenoiserTileList, int(groupId)).x;
    const ivec2 dispatchThreadId         = ivec2(packedCoords & 0xffffu, (packedCoords >> 16) & 0xffffu) + groupThreadId;
    const ivec2 dispatchGroupId          = dispatchThreadId / 8;
    const uvec2 remappedGroupThreadId    = FFX_DNSR_Reflections_RemapLane8x8(groupIndex);
    const uvec2 remappedDispatchThreadId = dispatchGroupId * 8 + remappedGroupThreadId;

    FFX_DNSR_Reflections_ResolveTemporal(ivec2(remappedDispatchThreadId), ivec2(remappedGroupThreadId), g_Size, g_TexelSize, g_TemporalStabilityFactor);
}