#include "defines.h"
#include "postprocessing/utils.h"

layout(push_constant) uniform PushData
{
    uint g_NumPixels;
    float g_TimeCoef;
    float g_MinLog2Lum;
    float g_LogLumRange;
    float g_AdaptationKey;
};

layout(binding = 0) buffer Histogram
{
    uint g_Histogram[];
};

layout(binding = 1) buffer Exposure
{
    float g_Exposure;
    float g_AverageLuminance;
};

#define GROUP_SIZE 16
layout(local_size_x = GROUP_SIZE * GROUP_SIZE, local_size_y = 1) in;

shared uint histogramShared[GROUP_SIZE * GROUP_SIZE];

void main()
{
    // Get the count from the histogram buffer
    const uint countForThisBin = g_Histogram[gl_LocalInvocationIndex];
    histogramShared[gl_LocalInvocationIndex] = countForThisBin * gl_LocalInvocationIndex;

    memoryBarrierShared();
    barrier();

    // Reset the count stored in the buffer in anticipation of the next pass
    g_Histogram[gl_LocalInvocationIndex] = 0;

    // This loop will perform a weighted count of the luminance range
    for (uint cutoff = ((GROUP_SIZE * GROUP_SIZE) >> 1); cutoff > 0; cutoff >>= 1)
    {
        if (gl_LocalInvocationIndex < cutoff)
            histogramShared[gl_LocalInvocationIndex] += histogramShared[gl_LocalInvocationIndex + cutoff];
        memoryBarrierShared();
        barrier();
    }

    // We only need to calculate this once, so only a single thread is needed.
    if (gl_LocalInvocationIndex == 0)
    {
        // Here we take our weighted sum and divide it by the number of pixels
        // that had luminance greater than zero (since the index == 0, we can
        // use countForThisBin to find the number of black pixels)
        float weightedLogAverage = (histogramShared[0] / max(g_NumPixels - float(countForThisBin), 1.0)) - 1.0;

        // Map from our histogram space to actual luminance
        float weightedAvgLum = exp2(((weightedLogAverage / 254.0) * g_LogLumRange) + g_MinLog2Lum);

        // The new stored value will be interpolated using the last frames value
        // to prevent sudden shifts in the exposure.
        float lumLastFrame = g_AverageLuminance;
        float adaptedLum = lumLastFrame + (weightedAvgLum - lumLastFrame) * g_TimeCoef;
        g_AverageLuminance = adaptedLum;
        g_Exposure = g_AdaptationKey / max(g_AverageLuminance, 0.0001f);
   }
}
