#include "defines.h"
#include "postprocessing/utils.h"
#include "utils.h"

layout(push_constant) uniform PushData
{
    vec3 AgXSlope;
    float g_InvGamma;
    vec3 AgXPower;
    float g_PhotolinearScale;
    vec3 AgXOffset;
    float g_WhitePoint;
    ivec2 g_Size;
    float AgXSaturation;
};

layout(binding = 0, r11f_g11f_b10f) uniform readonly image2D g_Color;
layout(binding = 1, OUTPUT_FORMAT) uniform writeonly image2D g_Output;
layout(binding = 2) readonly buffer Exposure
{
    float g_Exposure;
    float g_AverageLuminance;
};

layout(constant_id = 0) const uint g_TonemappingMethod = TONE_MAPPING_AgX;

#define GROUP_SIZE 8
layout(local_size_x = GROUP_SIZE, local_size_y = GROUP_SIZE) in;

void main()
{
    const ivec2 pixelCoords = ivec2(gl_GlobalInvocationID);
    if (pixelCoords.x >= g_Size.x || pixelCoords.y >= g_Size.y)
        return;

    AgXParams agx;
    agx.Slope = AgXSlope;
    agx.Power = AgXPower;
    agx.Offset = AgXOffset;
    agx.Saturation = AgXSaturation;

    vec3 color = imageLoad(g_Color, pixelCoords).rgb;
    color = ApplyTonemapping(g_TonemappingMethod, color, g_Exposure, g_WhitePoint, g_PhotolinearScale, agx);
    if (g_TonemappingMethod != TONE_MAPPING_PHOTO_LINEAR)
        color = ApplyGamma(color, g_InvGamma);

    imageStore(g_Output, pixelCoords, vec4(color, 1.f));
}
