#extension GL_EXT_scalar_block_layout : require

#include "defines.h"
#include "skin_cache/skin_cache_utils.h"

layout(scalar, binding = 0)
buffer MeshAABBsBuffer
{
    AABB g_AABBs[];
};

layout(push_constant) uniform PushData
{
    uint g_Count;
};

#define GROUP_SIZE 128
layout(local_size_x = GROUP_SIZE) in;

void main()
{
    const uint index = gl_GlobalInvocationID.x;
    if (index >= g_Count)
    {
        return;
    }

    const AABB aabb = g_AABBs[index];

    g_AABBs[index].Min = uintSortableToFloat(floatBitsToUint(aabb.Min));
    g_AABBs[index].Max = uintSortableToFloat(floatBitsToUint(aabb.Max));
}
