#extension GL_EXT_nonuniform_qualifier : enable
#extension GL_KHR_shader_subgroup_arithmetic : require
#extension GL_EXT_scalar_block_layout : require

#include "defines.h"
#include "utils.h"
#include "skin_cache/skin_cache_utils.h"

#include "skeletal_mesh_vertex_input_layout.h"

layout(scalar, set = 0, binding = 0)
readonly buffer Vertices
{
    SkeletalVertex g_Vertices[];
};

layout(scalar, set = 0, binding = 1)
buffer SkinnedVertices
{
    Vertex g_SkinnedVertices[];
};

layout(set = 0, binding = 2)
readonly buffer MeshTransformsBuffer
{
    mat4 g_Transforms[];
};

layout(scalar, set = 0, binding = 3)
buffer MeshAABBsBuffer
{
    UAABB g_AABBs[];
};

#ifdef EG_OUTPUT_PREV_POSITION
layout(scalar, set = 0, binding = 4)
buffer PrevSkinnedVertices
{
    vec3 g_PrevSkinnedVerticesPositions[];
};
#endif

layout(set = 1, binding = 0)
readonly buffer MeshAnimTransformsBuffer
{
    mat4 Transforms[];
} g_MeshAnimation[];

layout(push_constant) uniform PushData
{
    uint g_VerticesCount;
	uint g_VerticesOffset;
	uint g_DstOffset;
	uint g_AnimIndex;
#ifdef EG_OUTPUT_PREV_POSITION
    uint g_PrevVerticesValid;
#endif
};

shared UAABB s_AABB;

#define GROUP_SIZE 128
layout(local_size_x = GROUP_SIZE) in;

void main()
{
    const uint threadID = gl_GlobalInvocationID.x;
    if (threadID >= g_VerticesCount)
    {
        return;
    }

    const uint threadIndex = gl_LocalInvocationIndex;
    if (threadIndex == 0)
	{
		s_AABB.Min = floatToUintSortable(vec3(+FLT_MAX));
		s_AABB.Max = floatToUintSortable(vec3(-FLT_MAX));
	}

    const uint vertexIndex = threadID + g_VerticesOffset;
    const uint dstIndex = g_DstOffset + threadID;

    SkeletalVertex vertex = g_Vertices[vertexIndex];
#ifdef EG_OUTPUT_PREV_POSITION
    if (g_PrevVerticesValid == 1u)
    {
        g_PrevSkinnedVerticesPositions[dstIndex] = g_SkinnedVertices[dstIndex].Position;
    }
#endif

    mat4 boneTransform = mat4(0.f);
    for (uint i = 0; i < 4; ++i)
    {
        const float weight = GetWeight(vertex, i);
        if (weight > 0.f)
        {
            boneTransform += g_MeshAnimation[g_AnimIndex].Transforms[GetBoneID(vertex, i)] * weight;
        }
    }

    // They're the same
    const uint transformIndex = g_AnimIndex;
    const vec4 vertexPosition = boneTransform * vec4(vertex.Position, 1.0);

    Vertex skinnedVertex;
    skinnedVertex.Position = (g_Transforms[transformIndex] * vertexPosition).xyz;
    skinnedVertex.Normal   = normalize(mat3(boneTransform) * vertex.Normal);
    skinnedVertex.Tangent  = normalize(mat3(boneTransform) * vertex.Tangent);
    skinnedVertex.TexCoords  = vertex.TexCoords;
#ifdef EG_OUTPUT_PREV_POSITION
    if (g_PrevVerticesValid == 0u)
    {
        // If invalid, copy the most up to date position
        g_PrevSkinnedVerticesPositions[dstIndex] = skinnedVertex.Position;
    }
#endif

    g_SkinnedVertices[dstIndex] = skinnedVertex;

    // Calculate AABB min/max
    {
        barrier();

        const vec3 aabbMin = subgroupMin(vertexPosition.xyz);
	    const vec3 aabbMax = subgroupMax(vertexPosition.xyz);
	    if (subgroupElect())
	    {
            doAtomicMin(s_AABB.Min, floatToUintSortable(aabbMin));
            doAtomicMax(s_AABB.Max, floatToUintSortable(aabbMax));
	    }

        barrier();
        if (threadIndex == 0)
        {
            // Write to global memory
            doAtomicMin(g_AABBs[transformIndex].Min, s_AABB.Min);
            doAtomicMax(g_AABBs[transformIndex].Max, s_AABB.Max);
        }
    }
}
