#include "dof/common.h"

layout(binding = 0) uniform sampler2D g_Main;
layout(binding = 1) uniform sampler2D g_Alpha;

layout(binding = 2, r11f_g11f_b10f) uniform image2D g_PostFilter;
layout(binding = 3, r8) uniform image2D g_AlphaResult;

const vec2 circleOffsets[] =
{
	vec2( 0.7071, -0.7071 ),
	vec2(-0.7071,  0.7071 ),
	vec2(-1.0000,  0.0000 ),
	vec2( 1.0000,  0.0000 ),
	vec2( 0.0000,  0.0000 ),
	vec2(-0.7071, -0.7071 ),
	vec2( 0.7071,  0.7071 ),
	vec2(-0.0000, -1.0000 ),
	vec2( 0.0000,  1.0000 ),
};

layout(local_size_x = GROUP_SIZE, local_size_y = GROUP_SIZE) in;

void main()
{
    const ivec2 pixelCoords = ivec2(gl_GlobalInvocationID);
    if (pixelCoords.x >= g_PassSize.x || pixelCoords.y >= g_PassSize.y)
        return;

	float alpha;
	vec3 color;

	// Median filter [Smith1996]
	{
		float p[9];

		p[0] = texture(g_Alpha, (pixelCoords + circleOffsets[0]) * g_TexelSize).x;
		p[1] = texture(g_Alpha, (pixelCoords + circleOffsets[1]) * g_TexelSize).x;
		p[2] = texture(g_Alpha, (pixelCoords + circleOffsets[2]) * g_TexelSize).x;
		sort3(p[0], p[1], p[2]);

		p[3] = texture(g_Alpha, (pixelCoords + circleOffsets[3]) * g_TexelSize).x;
		p[4] = texture(g_Alpha, (pixelCoords + circleOffsets[4]) * g_TexelSize).x;
		p[5] = texture(g_Alpha, (pixelCoords + circleOffsets[5]) * g_TexelSize).x;
		sort3(p[3], p[4], p[5]);

		p[6] = texture(g_Alpha, (pixelCoords + circleOffsets[6]) * g_TexelSize).x;
		p[7] = texture(g_Alpha, (pixelCoords + circleOffsets[7]) * g_TexelSize).x;
		p[8] = texture(g_Alpha, (pixelCoords + circleOffsets[8]) * g_TexelSize).x;
		sort3(p[6], p[7], p[8]);

		p[6] = EG_max3(p[0], p[3], p[6]);
		p[2] = EG_min3(p[2], p[5], p[8]);

		sort3(p[1], p[4], p[7]);
		sort3(p[2], p[4], p[6]);

		alpha = p[4];
	}

	{
		vec3 p[9];

		p[0] = texture(g_Main, (pixelCoords + circleOffsets[0]) * g_TexelSize).rgb;
		p[1] = texture(g_Main, (pixelCoords + circleOffsets[1]) * g_TexelSize).rgb;
		p[2] = texture(g_Main, (pixelCoords + circleOffsets[2]) * g_TexelSize).rgb;
		sort3(p[0], p[1], p[2]);

		p[3] = texture(g_Main, (pixelCoords + circleOffsets[3]) * g_TexelSize).rgb;
		p[4] = texture(g_Main, (pixelCoords + circleOffsets[4]) * g_TexelSize).rgb;
		p[5] = texture(g_Main, (pixelCoords + circleOffsets[5]) * g_TexelSize).rgb;
		sort3(p[3], p[4], p[5]);

		p[6] = texture(g_Main, (pixelCoords + circleOffsets[6]) * g_TexelSize).rgb;
		p[7] = texture(g_Main, (pixelCoords + circleOffsets[7]) * g_TexelSize).rgb;
		p[8] = texture(g_Main, (pixelCoords + circleOffsets[8]) * g_TexelSize).rgb;
		sort3(p[6], p[7], p[8]);

		p[6] = EG_max3(p[0], p[3], p[6]);
		p[2] = EG_min3(p[2], p[5], p[8]);

		sort3(p[1], p[4], p[7]);
		sort3(p[2], p[4], p[6]);

		color = p[4];
	}

	imageStore(g_PostFilter, pixelCoords, vec4(color, 0));
	imageStore(g_AlphaResult, pixelCoords, vec4(alpha));
}
