#include "dof/common.h"

layout(binding = 0) uniform sampler2D g_Depth;
layout(binding = 1, rg16f) uniform writeonly image2D g_TileMinDepthMaxCOC;
layout(binding = 2, r16f) uniform writeonly image2D g_TileMinCOC;

layout(local_size_x = GROUP_SIZE, local_size_y = GROUP_SIZE) in;

void main()
{
    const ivec2 pixelCoords = ivec2(gl_GlobalInvocationID);
    if (pixelCoords.x >= g_PassSize.x || pixelCoords.y >= g_PassSize.y)
        return;

	const uvec2 tileUpperleft = uvec2(pixelCoords.x * DOF_TILESIZE, pixelCoords.y);
	float closestDepth = g_ZFar;
	float minCOC = g_MaxCOC;
	float maxCOC = 0;

	for (uint i = 0; i < DOF_TILESIZE; ++i)
	{
		const uvec2 pixel = uvec2(tileUpperleft.x + i, tileUpperleft.y);
		if (pixel.x >= 0 && pixel.y >= 0 && pixel.x < g_Size.x && pixel.y < g_Size.y)
		{
			const vec2 uv = (pixel + 0.5) * g_TexelSize;
			const float depth = ToLinear(texture(g_Depth, uv).x);
			const float coc = GetCOC(depth);
			closestDepth = min(closestDepth, depth);
			minCOC = min(minCOC, coc);
			maxCOC = max(maxCOC, coc);
		}
	}

	imageStore(g_TileMinCOC, pixelCoords, vec4(minCOC));
	imageStore(g_TileMinDepthMaxCOC, pixelCoords, vec4(closestDepth, maxCOC, 0.f, 0.f));
}
