#include "dof/common.h"

layout(binding = 0) uniform sampler2D g_PostFilter;
layout(binding = 1) uniform sampler2D g_Alpha;
layout(binding = 2, rg16f) uniform image2D g_NeighborHoodMinMax;
layout(binding = 3) uniform sampler2D g_Depth;

layout(binding = 4, r11f_g11f_b10f) uniform image2D g_Color;

layout(local_size_x = GROUP_SIZE, local_size_y = GROUP_SIZE) in;

void main()
{
    const ivec2 pixelCoords = ivec2(gl_GlobalInvocationID);
    if (pixelCoords.x >= g_PassSize.x || pixelCoords.y >= g_PassSize.y)
        return;

    const vec2 uv = (pixelCoords + 0.5f) * g_TexelSize;

	const float centerDepth = ToLinear(texture(g_Depth, uv).x);
	const vec2 minDepth_maxcoc = imageLoad(g_NeighborHoodMinMax, pixelCoords / DOF_TILESIZE).xy;
	const float minDepth = minDepth_maxcoc.x;
	const float maxcoc = minDepth_maxcoc.y;
	const vec3 halfres = texture(g_PostFilter, uv).rgb;
	const float alpha = texture(g_Alpha, uv).x;

	const float coc = GetCOC(centerDepth);

	const float depthDelta = clamp(1.0 - (centerDepth - minDepth), 0.f, 1.f);

	const float backgroundFactor = coc;
	const float foregroundFactor = mix(maxcoc, coc, depthDelta);

	const float combinedFactor = clamp(mix(backgroundFactor, foregroundFactor, alpha), 0.f, 1.f);

	const vec3 color = imageLoad(g_Color, pixelCoords).rgb;
	const vec3 resultColor = mix(color, halfres, combinedFactor);

	imageStore(g_Color, pixelCoords, vec4(resultColor, 1.f));
}
