// Source: https://therealmjp.github.io/posts/deferred-msaa/

#include "defines.h"
#include "utils.h"

layout(push_constant) uniform PushConstants
{
	vec3 g_CameraPos;
    float g_EdgeThreshold;
    ivec2 g_Size;
    float g_Near;
    float g_Far;
	uint g_VisualizeEdges;
};

layout(binding = 0, rgba8) uniform image2D g_Result;
layout(binding = 1) uniform sampler2D g_ResultBilinear;
layout(binding = 2) uniform sampler2DMS g_MSAADepth;
layout(binding = 3) uniform sampler2DMS g_MSAANormals;
layout(binding = 4) uniform sampler2D g_Depth;
layout(binding = 5) uniform sampler2D g_Normals;

layout(binding = 6)
uniform CameraView
{
	mat4 g_View;
	mat4 g_ViewProjInv;
	mat4 g_ViewProj;
	mat4 g_PrevViewProj;
	mat4 g_Proj;
	mat4 g_InvProj;
};

#define GROUP_SIZE 8
layout(local_size_x = GROUP_SIZE, local_size_y = GROUP_SIZE) in;

float ToLinear(float depth)
{
	return ToLinear(depth, g_Near, g_Far);
}

// MSAA sampling pattern
#if EG_MSAA_SAMPLES == 2
const vec2 s_SamplePoints[2] = vec2[](
    vec2(0.750, 0.750),
    vec2(0.250, 0.250)
);
#elif EG_MSAA_SAMPLES == 4
const vec2 s_SamplePoints[4] = vec2[](
    vec2(0.380, 0.141),
    vec2(0.859, 0.380),
    vec2(0.141, 0.620),
    vec2(0.620, 0.859)
);
#elif EG_MSAA_SAMPLES == 8
const vec2 s_SamplePoints[8] = vec2[](
    vec2(0.5625, 0.3125),
    vec2(0.4375, 0.6875),
    vec2(0.8125, 0.5625),
    vec2(0.3125, 0.1875),
    vec2(0.1875, 0.8125),
    vec2(0.0625, 0.4375),
    vec2(0.6875, 0.9375),
    vec2(0.9375, 0.0625)
);
#endif

void main()
{
    const ivec2 pixelCoords = ivec2(gl_GlobalInvocationID);
    if (pixelCoords.x >= g_Size.x || pixelCoords.y >= g_Size.y)
        return;

	float depth = texelFetch(g_Depth, pixelCoords, 0).x;
	if (depth == EG_DEPTH_FAR)
		return;

    const vec2 texelSize = 1.f / g_Size;
    const vec2 uv = (pixelCoords + 0.5) * texelSize;
    const vec3 worldPos = WorldPosFromDepth(g_ViewProjInv, uv, depth);
	const vec3 fragToCam = g_CameraPos - worldPos;
	const float dist = length(fragToCam);
	const vec3 viewDir = fragToCam / dist;

    depth = ToLinear(depth);
    const vec3 normal = DecodeNormal(texelFetch(g_Normals, pixelCoords, 0).xy);
	const float viewAngle = clamp(dot(viewDir, normal), 0.0f, 1.0f);

	// Calculate edge threshold heuristic. Obtained empirically
	// The bigger the angle, the bigger the threshold.
	// The bigger the distance, the bigger the threshold.
	// Not sure if there's a better way
	const float viewAngleCoef = (1 - viewAngle) * (1 - viewAngle);
	const float distCoef = dist * 0.05;
	const float edgeThreshold = mix(g_EdgeThreshold, 1, distCoef * viewAngleCoef);
	
    const vec4 inputColor = imageLoad(g_Result, pixelCoords);
	vec3 outputColor = vec3(0);

    // Loop through the MSAA samples and compare with the non-MSAA depth
	bool bAnyEdge = false;
	for (int i = 0; i < EG_MSAA_SAMPLES; ++i)
	{
		const float msDepth = ToLinear(texelFetch(g_MSAADepth, pixelCoords, i).x);
		const vec3 msNormal = DecodeNormal(texelFetch(g_MSAANormals, pixelCoords, i).xy);

		const bool bEdge = abs(depth - msDepth) >= edgeThreshold || dot(normal, msNormal) < 0.9f;
		bAnyEdge = bAnyEdge || bEdge;

		if(!bEdge)
		{
			outputColor += inputColor.rgb;
		}
		else
		{	
			// Take a new sample for each MSAA sample that's on the edge
			vec2 samplePoint = vec2(pixelCoords) + (s_SamplePoints[i] - vec2(0.5f)) * 2;
			vec2 sampleCoord = samplePoint / g_Size;
			outputColor += texture(g_ResultBilinear, sampleCoord).rgb;
		}		
	}

	const bool bEnableVis = g_VisualizeEdges != 0u && bAnyEdge;
	outputColor.rgb = bEnableVis ? vec3(1, 0, 0) : outputColor / EG_MSAA_SAMPLES;
	imageStore(g_Result, pixelCoords, vec4(outputColor.rgb, inputColor.a));
}
