#extension GL_EXT_scalar_block_layout : require

#include "defines.h"
#include "utils.h"

struct MeshData
{
	vec3 MinAABB;
	uint MaterialsCount;
	vec3 MaxAABB;
	uint MaterialsOffset;
	uint VertexOffset;
};

struct MaterialData
{
	uint FirstIndex;
	uint IndexCount;
	uint FirstInstance;
	uint InstanceCount;
};

#ifdef EG_SKELETAL
#include "skeletal_mesh_vertex_input_layout.h"
#else
#define EG_COMPUTE_VERTEX_LAYOUT
#include "mesh_vertex_input_layout.h"
#endif

struct DrawIndexedIndirectCommand
{
    uint IndexCount;
    uint InstanceCount;
    uint FirstIndex;
    int  VertexOffset;
    uint FirstInstance;
};

layout(scalar, binding = 0) readonly buffer MeshDataBuffer
{
    MeshData g_Meshes[];
};

layout(binding = 1) readonly buffer MaterialsDataBuffer
{
    MaterialData g_MaterialsData[];
};

layout(scalar, binding = 2) readonly buffer InstanceBuffer
{
    InstanceData g_Instances[];
};

layout(binding = 3) readonly buffer MeshTransformsBuffer
{
    mat4 g_Transforms[];
};

layout(scalar, binding = 4) buffer CulledInstanceBuffer
{
    InstanceData g_CulledInstances[];
};

layout(scalar, binding = 5) buffer UnculledInstanceBuffer
{
    InstanceData g_UnculledInstances[];
};

layout(scalar, binding = 6) buffer DrawCallsBuffer
{
    DrawIndexedIndirectCommand g_DrawCalls[];
};

layout(binding = 7) buffer DrawCallsCounterBuffer
{
    uint g_DrawCallsCounter;
};

layout(scalar, binding = 8) buffer UnculledDrawCallsBuffer
{
    DrawIndexedIndirectCommand g_UnculledDrawCalls[];
};

layout(binding = 9) buffer UnculledDrawCallsCounterBuffer
{
    uint g_UnculledDrawCallsCounter;
};

#ifdef EG_SKELETAL
struct SkeletalPushData
{
	uint VertexCount;
	uint InstanceOffset;
	uint VerticesOffset;
};

layout(scalar, binding = 10) readonly buffer InputSkeletalPushDataBuffer
{
    SkeletalPushData g_InputSkeletalPushData[];
};

struct AABB
{
	vec3 Min;
	vec3 Max;
};

layout(scalar, binding = 11) readonly buffer InputSkeletalAABBsBuffer
{
    AABB g_AABBs[];
};
#endif

layout(push_constant) uniform PushData
{
    mat4 g_View;
    CullingFrustum g_Frustum;
    uint g_NumMeshes;
    uint g_MeshOffset;
    uint g_MaxDrawCalls;
};

// Keep it at 32 (or lower), otherwise subgroup logic will have to be changed
#define GROUP_SIZE 32
layout(local_size_x = GROUP_SIZE) in;

shared uint s_InstanceCount;
shared uint s_UnculledInstanceCount;

void main()
{
    const uint meshIndex = g_MeshOffset + gl_WorkGroupID.x;
    const uint threadIndex = gl_LocalInvocationIndex;
    if (meshIndex >= g_NumMeshes)
    {
        return;
    }

    const MeshData mesh = g_Meshes[meshIndex];
    for (uint materialIndex = 0; materialIndex < mesh.MaterialsCount; ++materialIndex)
    {
        const uint dataIndex = mesh.MaterialsOffset + materialIndex;
        const MaterialData materialData = g_MaterialsData[dataIndex];
#ifdef EG_SKELETAL
        const SkeletalPushData pushData = g_InputSkeletalPushData[dataIndex];
#endif

        if (subgroupElect())
        {
            s_InstanceCount = 0;
            s_UnculledInstanceCount = 0;
        }

        for (uint i = threadIndex; i < materialData.InstanceCount; i += GROUP_SIZE)
        {
            const uint instanceIndex = materialData.FirstInstance + i;
            InstanceData instance = g_Instances[instanceIndex];
            const uint transformIndex = GetTransformIndex(instance);
            const mat4 model = g_Transforms[transformIndex];

#ifdef EG_SKELETAL
            instance.VertexOffset = pushData.VerticesOffset + pushData.VertexCount * i;

            const AABB aabb = g_AABBs[transformIndex];
            const vec3 aabbMin = aabb.Min;
            const vec3 aabbMax = aabb.Max;
#else
            const vec3 aabbMin = mesh.MinAABB;
            const vec3 aabbMax = mesh.MaxAABB;
#endif
            
            const bool bVisible = FrustumAABBIntersection(g_Frustum, g_View * model, aabbMin, aabbMax);
            if (bVisible)
            {
                uint offset;
                EG_SUBGROUP_ATOMIC_INCREMENT(s_InstanceCount, true, offset);
                g_CulledInstances[materialData.FirstInstance + offset] = instance;
            }

            if (DoesCastShadows(instance))
            {
                uint offset;
                EG_SUBGROUP_ATOMIC_INCREMENT(s_UnculledInstanceCount, true, offset);
                g_UnculledInstances[materialData.FirstInstance + offset] = instance;
            }
        }

        if (subgroupElect())
        {
            DrawIndexedIndirectCommand drawCall;
            drawCall.IndexCount = materialData.IndexCount;
            drawCall.FirstIndex = materialData.FirstIndex;
#ifdef EG_SKELETAL
            drawCall.VertexOffset = 0; // Skeletal vertices are fetched manually
#else
            drawCall.VertexOffset = int(mesh.VertexOffset);
#endif
            drawCall.FirstInstance = materialData.FirstInstance;

            if (s_InstanceCount > 0)
            {
                uint insertIdx = 0;
                EG_SUBGROUP_ATOMIC_INCREMENT(g_DrawCallsCounter, true, insertIdx)
                if (insertIdx < g_MaxDrawCalls)
                {
                    drawCall.InstanceCount = s_InstanceCount;
                    g_DrawCalls[insertIdx] = drawCall;
                }
            }

            if (s_UnculledInstanceCount > 0)
            {
                uint insertIdx = 0;
                EG_SUBGROUP_ATOMIC_INCREMENT(g_UnculledDrawCallsCounter, true, insertIdx)
                if (insertIdx < g_MaxDrawCalls)
                {
                    drawCall.InstanceCount = s_UnculledInstanceCount;
                    g_UnculledDrawCalls[insertIdx] = drawCall;
                }
            }
        }
    }
}
