#extension GL_EXT_nonuniform_qualifier : enable

#include "pbr_pipeline_layout.h"
#include "utils.h"
#define PBR_EVALUATE_IBL
#include "pbr_utils.h"

#define EG_PIXEL_COORDS vec2(gl_GlobalInvocationID)
#include "light_utils.h"

layout(set = 6, binding = 0, r11f_g11f_b10f) uniform image2D g_Result;

layout(push_constant) uniform PushConstants
{
    vec3 g_CameraPos;
    float g_MaxReflectionLOD;
    ivec2 g_Size;
    float g_CSMOverlap;
    float g_IBLIntensity;
    uint g_TilesBufferWidth;
    uint g_HasDirLight;
};

layout(constant_id = 0) const bool s_HasIrradiance = false;

vec3 GTAOMultiBounce(vec3 albedo, float ao)
{
    const vec3 a =  2.0404f * albedo - 0.3324f;
    const vec3 b = -4.7951f * albedo + 0.6417f;
    const vec3 c =  2.7552f * albedo + 0.6903f;

    return max(vec3(ao), ((a * ao + b) * ao + c) * ao);
}

#define GROUP_SIZE 8
layout(local_size_x = GROUP_SIZE, local_size_y = GROUP_SIZE) in;

void main()
{
    const ivec2 pixelCoords = ivec2(gl_GlobalInvocationID);
    if (pixelCoords.x >= g_Size.x || pixelCoords.y >= g_Size.y)
        return;

    const vec2 texelSize = 1.f / g_Size;
    const vec2 uv = (pixelCoords + 0.5) * texelSize;

    const vec3 albedo = texture(g_AlbedoTexture, uv).rgb;
    const vec3 lambertAlbedo = albedo * EG_INV_PI;
    const float depth = texture(g_DepthTexture, uv).x;
    if (depth == EG_DEPTH_FAR)
    {
        return;
    }

    const vec3 worldPos = WorldPosFromDepth(g_ViewProjInv, uv, depth);
    const vec3 materialData = texture(g_MaterialDataTexture, uv).xyz;

    const float metalness = materialData.x;
    const float ao = materialData.y;
    const float roughness = materialData.z;
    const vec3 F0 = mix(vec3(EG_BASE_REFLECTIVITY), albedo, metalness);

    const vec3 fragToCamera = g_CameraPos - worldPos;
    const vec3 V = normalize(fragToCamera);

    vec3 Lo = vec3(0.f);
    const vec4 encodedNormals = texture(g_GeometryShadingNormalsTexture, uv); // xy - geometry, zw - shading
    const vec3 geometryNormal = DecodeNormal(encodedNormals.xy);
    const vec3 shadingNormal = DecodeNormal(encodedNormals.zw);

    const uvec2 tileID = pixelCoords / EG_LIGHT_CULLING_TILE_SIZE;
    const uint tileIndex = tileID.x + tileID.y * g_TilesBufferWidth;
    const uint bucketStartIndex = tileIndex * EG_LIGHTS_BUCKET_COUNT;

    // PointLights
    const uint pointLightsBucketsCount = g_PointLightsCount > 0 ? min(EG_LIGHTS_BUCKET_COUNT, ((g_PointLightsCount - 1) / EG_LIGHT_BUCKET_SIZE) + 1) : 0u;
    for (uint bucket = 0; bucket < pointLightsBucketsCount; bucket++)
    {
        uint bucketBits = g_PointLightsBuckets[bucketStartIndex + bucket];
        while(bucketBits > 0)
        {
            const uint bucketLightIndex = findLSB(bucketBits);
            const uint lightIndex = EG_LIGHT_BUCKET_SIZE * bucket + bucketLightIndex;
            bucketBits ^= (1 << bucketLightIndex);

            const PointLight pointLight = g_PointLights[lightIndex];
            Lo += CalculatePointLightRadiance(pointLight, worldPos, geometryNormal, shadingNormal, lambertAlbedo, V, F0, metalness, roughness);
        }
    }

    // SpotLights
    const uint spotLightsBucketsCount = g_SpotLightsCount > 0 ? min(EG_LIGHTS_BUCKET_COUNT, ((g_SpotLightsCount - 1) / EG_LIGHT_BUCKET_SIZE) + 1) : 0u;
    for (uint bucket = 0; bucket < spotLightsBucketsCount; bucket++)
    {
        uint bucketBits = g_SpotLightsBuckets[bucketStartIndex + bucket];
        while(bucketBits > 0)
        {
            const uint bucketLightIndex = findLSB(bucketBits);
            const uint lightIndex = EG_LIGHT_BUCKET_SIZE * bucket + bucketLightIndex;
            bucketBits ^= (1 << bucketLightIndex);

            const SpotLight spotLight = g_SpotLights[lightIndex];
            Lo += CalculateSpotLightRadiance(spotLight, worldPos, geometryNormal, shadingNormal, lambertAlbedo, V, F0, metalness, roughness);
        }
    }

    // Directional light
#ifdef EG_ENABLE_CSM_VISUALIZATION
    vec3 cascadeVisualizationColor = vec3(0.f);
#endif

    if (g_HasDirLight != 0)
    {
        Lo += CalculateDirectionalLightRadiance(g_DirectionalLight, worldPos, geometryNormal, shadingNormal, lambertAlbedo, V, F0, metalness, roughness,
            g_CameraView, g_CSMOverlap
#ifdef EG_ENABLE_CSM_VISUALIZATION
            , cascadeVisualizationColor
#endif
        );
    }

    // Ambient
    vec3 ambient = (g_HasDirLight != 0) ? (albedo * g_DirectionalLight.Ambient) : vec3(0.f);
    if (s_HasIrradiance)
    {
        const vec3 shadingNormal = DecodeNormal(encodedNormals.zw);
        ambient += EvaluateIBL(albedo, F0, shadingNormal, V, roughness, metalness, g_MaxReflectionLOD) * ao * g_IBLIntensity;
    }
#ifdef EG_SSAO
    ambient *= GTAOMultiBounce(albedo, texture(g_SSAO, uv).x);
#endif

    vec3 resultColor = ambient + Lo + texture(g_EmissiveTexture, uv).xyz;
#ifdef EG_ENABLE_CSM_VISUALIZATION
    resultColor += cascadeVisualizationColor;
#endif

    vec4 color = imageLoad(g_Result, pixelCoords);
    color.rgb += resultColor;
    imageStore(g_Result, pixelCoords, color);
}
