#extension GL_EXT_nonuniform_qualifier : enable

#include "defines.h"
#include "utils.h"
#include "common_structures.h"

layout(set = 0, binding = 0, r11f_g11f_b10f) uniform writeonly image2D g_Result;
layout(set = 0, binding = 1) uniform sampler2D g_DepthTexture;
layout(set = 0, binding = 2) uniform sampler2D g_GeometryShadingNormalsTexture;
layout(set = 0, binding = 3) buffer IndirectArgs
{
    uvec4 g_DispatchArgs;
};

layout(set = 1, binding = 0)
readonly buffer PointLightsBuffer
{
    PointLight g_PointLights[];
};

layout(set = 1, binding = 1)
readonly buffer SpotLightsBuffer
{
    SpotLight g_SpotLights[];
};

layout(set = 1, binding = 2)
readonly buffer PointLightsBucketsBuffer
{
	uint g_PointLightsBuckets[];
};

layout(set = 1, binding = 3)
readonly buffer SpotLightsBucketsBuffer
{
	uint g_SpotLightsBuckets[];
};

layout(set = 1, binding = 4)
uniform LightsCounterBuffer
{
	uint g_PointLightsCount;
	uint g_SpotLightsCount;
};

layout(set = 1, binding = 5)
readonly buffer DirectionalLightBuffer
{
    DirectionalLight g_DirectionalLight;
};

layout(set = 1, binding = 6)
uniform CameraView
{
    mat4 g_CameraView;
    mat4 g_ViewProjInv;
};

layout(set = 1, binding = 7)
readonly buffer LightMatricesBuffer
{
	mat4 g_LightMatrices[];
};

layout(set = 2, binding = 0) uniform sampler2DShadow   g_DirShadowMaps[EG_CASCADES_COUNT];
layout(set = 3, binding = 0) uniform samplerCubeShadow g_PointShadowMaps[];
layout(set = 4, binding = 0) uniform sampler2DShadow   g_SpotShadowMaps[];

#ifdef EG_TRANSLUCENT_SHADOWS
layout(set = 5, binding = 0) uniform sampler2D   g_DirShadowMapsColored[EG_CASCADES_COUNT];
layout(set = 6, binding = 0) uniform samplerCube g_PointShadowMapsColored[];
layout(set = 7, binding = 0) uniform sampler2D   g_SpotShadowMapsColored[];

layout(set = 8, binding = 0)  uniform sampler2D   g_DirShadowMapsColoredDepth[EG_CASCADES_COUNT];
layout(set = 9, binding = 0)  uniform samplerCube g_PointShadowMapsColoredDepth[];
layout(set = 10, binding = 0) uniform sampler2D   g_SpotShadowMapsColoredDepth[];
#endif

layout(push_constant) uniform PushConstants
{
    vec3 g_CameraPos;
    float g_VolumetricMaxDistance;
    ivec2 g_Size;
    float g_Time;
    uint g_DownscaleFactor;
    vec3 g_FogAlbedo;
    float g_FogAnisotropy;
    float g_Near;
    uint g_TilesBufferWidth;
    uint g_HasDirLight;
};

layout(constant_id = 0) const uint s_VolumetricSamples = 20;

#define EG_PIXEL_COORDS vec2(gl_GlobalInvocationID)
#include "volumetric_utils.h"

#define GROUP_SIZE 8
layout(local_size_x = GROUP_SIZE, local_size_y = GROUP_SIZE) in;

void main()
{
    const ivec2 pixelCoords = ivec2(gl_GlobalInvocationID);
    if (pixelCoords.x >= g_Size.x || pixelCoords.y >= g_Size.y)
        return;

    const vec2 texelSize = 1.f / g_Size;
    const vec2 uv = (pixelCoords + 0.5) * texelSize;

    const float depth = texture(g_DepthTexture, uv).x;
    const vec3 worldPos = WorldPosFromDepth(g_ViewProjInv, uv, depth);

    vec3 Lo = vec3(0.f);
    const vec3 geometryNormal = DecodeNormal(texture(g_GeometryShadingNormalsTexture, uv).xy); // xy - geometry, zw - shading

    // Upscale to full-res to get correct tile ID
    const uvec2 tileID = (pixelCoords * g_DownscaleFactor) / EG_LIGHT_CULLING_TILE_SIZE;
    const uint tileIndex = tileID.x + tileID.y * g_TilesBufferWidth;
    const uint bucketStartIndex = tileIndex * EG_LIGHTS_BUCKET_COUNT;

    // PointLights
    const uint pointLightsBucketsCount = g_PointLightsCount > 0 ? min(EG_LIGHTS_BUCKET_COUNT, ((g_PointLightsCount - 1) / EG_LIGHT_BUCKET_SIZE) + 1) : 0u;
    for (uint bucket = 0; bucket < pointLightsBucketsCount; bucket++)
    {
        uint bucketBits = g_PointLightsBuckets[bucketStartIndex + bucket];
        while(bucketBits > 0)
        {
            const uint bucketLightIndex = findLSB(bucketBits);
            const uint lightIndex = EG_LIGHT_BUCKET_SIZE * bucket + bucketLightIndex;
            bucketBits ^= (1 << bucketLightIndex);

            const PointLight pointLight = g_PointLights[lightIndex];
	        const bool bVolumetricLight = pointLight.VolumetricFogIntensity < 0;
	        if (!bVolumetricLight)
		        continue;

            const uint shadowMapIndex = pointLight.ShadowMapIndex;
            const vec3 incoming = pointLight.Position - worldPos;
            const bool bCastsShadows = pointLight.Radius2 < 0;
            const bool bCheckShadows = shadowMapIndex < EG_MAX_LIGHT_SHADOW_MAPS;

            if (bCastsShadows)
            {
                Lo += PointLight_Volumetric(pointLight, g_PointShadowMaps[nonuniformEXT(shadowMapIndex)],
    #ifdef EG_TRANSLUCENT_SHADOWS
                    g_PointShadowMapsColored[nonuniformEXT(shadowMapIndex)], g_PointShadowMapsColoredDepth[nonuniformEXT(shadowMapIndex)],
    #endif
                    worldPos, g_CameraPos, geometryNormal, s_VolumetricSamples, g_VolumetricMaxDistance, bCheckShadows);
            }
            else
            {
                Lo += PointLight_Volumetric(pointLight, g_PointShadowMaps[0],
    #ifdef EG_TRANSLUCENT_SHADOWS
                    g_PointShadowMapsColored[0], g_PointShadowMapsColoredDepth[0],
    #endif
                    worldPos, g_CameraPos, geometryNormal, s_VolumetricSamples, g_VolumetricMaxDistance, false);
            }
        }
    }

    // SpotLights
    const uint spotLightsBucketsCount = g_SpotLightsCount > 0 ? min(EG_LIGHTS_BUCKET_COUNT, ((g_SpotLightsCount - 1) / EG_LIGHT_BUCKET_SIZE) + 1) : 0u;
    for (uint bucket = 0; bucket < spotLightsBucketsCount; bucket++)
    {
        uint bucketBits = g_SpotLightsBuckets[bucketStartIndex + bucket];
        while(bucketBits > 0)
        {
            const uint bucketLightIndex = findLSB(bucketBits);
            const uint lightIndex = EG_LIGHT_BUCKET_SIZE * bucket + bucketLightIndex;
            bucketBits ^= (1 << bucketLightIndex);

            const SpotLight spotLight = g_SpotLights[lightIndex];
	        const bool bVolumetricLight = spotLight.VolumetricFogIntensity < 0;
	        if (!bVolumetricLight)
		        continue;

            const uint shadowMapIndex = spotLight.ShadowMapIndex;
            const vec3 incoming = spotLight.Position - worldPos;
            const bool bCastsShadows = spotLight.bCastsShadows != 0;
            const bool bCheckShadows = shadowMapIndex < EG_MAX_LIGHT_SHADOW_MAPS;

            if (bCastsShadows)
            {
                Lo += SpotLight_Volumetric(spotLight, g_SpotShadowMaps[nonuniformEXT(shadowMapIndex)],
    #ifdef EG_TRANSLUCENT_SHADOWS
                    g_SpotShadowMapsColored[nonuniformEXT(shadowMapIndex)], g_SpotShadowMapsColoredDepth[nonuniformEXT(shadowMapIndex)],
    #endif
                    worldPos, g_CameraPos, geometryNormal, s_VolumetricSamples, g_VolumetricMaxDistance, bCheckShadows);
            }
            else
            {
                Lo += SpotLight_Volumetric(spotLight, g_SpotShadowMaps[0],
    #ifdef EG_TRANSLUCENT_SHADOWS
                    g_SpotShadowMapsColored[0], g_SpotShadowMapsColoredDepth[0],
    #endif
                    worldPos, g_CameraPos, geometryNormal, s_VolumetricSamples, g_VolumetricMaxDistance, false);
            }
        }
    }

    if (g_HasDirLight != 0)
    {
	    const bool bVolumetricLight = g_DirectionalLight.VolumetricFogIntensity < 0;
	    if (bVolumetricLight)
        {
            const vec3 incoming = normalize(-g_DirectionalLight.Direction);
            Lo += DirectionalLight_Volumetric(g_DirectionalLight, g_DirShadowMaps,
#ifdef EG_TRANSLUCENT_SHADOWS
                g_DirShadowMapsColored, g_DirShadowMapsColoredDepth,
#endif
                worldPos, g_CameraPos, incoming, geometryNormal, g_CameraView, s_VolumetricSamples, g_VolumetricMaxDistance);
        }
    }

    Lo *= g_FogAlbedo;
    imageStore(g_Result, pixelCoords, vec4(Lo, 1.f));

    if (any(greaterThan(Lo, vec3(0))))
    {
        // We just need an indication that we have something on the screen that's worth applying
        g_DispatchArgs.x = 1;
    }
}
