#include "motion_blur/common.h"

layout(binding = 0, rg16f) uniform readonly image2D g_TileMin;
layout(binding = 1, rg16f) uniform readonly image2D g_TileMax;
layout(binding = 2, rg16f) uniform writeonly image2D g_NeighborHoodMax;

layout(binding = 3) buffer Tiles
{
	uvec4 EarlyExit;
	uvec4 Cheap;
	uvec4 Expensive;
} g_TileArgs;

layout(binding = 4) buffer EarlyExitTiles
{
	uint g_EarlyExitTiles[];
};

layout(binding = 5) buffer CheapTiles
{
	uint g_CheapTiles[];
};

layout(binding = 6) buffer ExpensiveTiles
{
	uint g_ExpensiveTiles[];
};

layout(local_size_x = GROUP_SIZE, local_size_y = GROUP_SIZE) in;

void main()
{
    const ivec2 pixelCoords = ivec2(gl_GlobalInvocationID);
    if (pixelCoords.x >= g_PassSize.x || pixelCoords.y >= g_PassSize.y)
        return;

	float minMagnitudeSquared = FLT_MAX;
	vec2 minVelocity = vec2(FLT_MAX);

	float maxMagnitudeSquared = 0;
	vec2 maxVelocity = vec2(0);

	for (int x = -1; x <= 1; ++x)
	{
		for (int y = -1; y <= 1; ++y)
		{
			const ivec2 pixel = pixelCoords.xy + ivec2(x, y);
			if (pixel.x >= 0 && pixel.y >= 0 && pixel.x < g_Size.x && pixel.y < g_Size.y)
			{
				vec2 velocity = imageLoad(g_TileMin, pixel).xy;
				float magnitudeSquared = dot(velocity, velocity);
				if (minMagnitudeSquared > magnitudeSquared)
				{
					minVelocity = velocity;
					minMagnitudeSquared = magnitudeSquared;
				}

				velocity = imageLoad(g_TileMax, pixel).xy;
				magnitudeSquared = dot(velocity, velocity);
				if(maxMagnitudeSquared < magnitudeSquared)
				{
					maxVelocity = velocity;
					maxMagnitudeSquared = magnitudeSquared;
				}
			}
		}
	}

	const uint tile = (pixelCoords.x & 0xFFFF) | ((pixelCoords.y & 0xFFFF) << 16);
	if (maxMagnitudeSquared < 0.0001f)
	{
		uint prev = atomicAdd(g_TileArgs.EarlyExit.x, MOTIONBLUR_TILE_REPLICATE); 
		g_EarlyExitTiles[prev / MOTIONBLUR_TILE_REPLICATE] = tile;
	}
	else if (abs(maxMagnitudeSquared - minMagnitudeSquared) < 0.0005f)
	{
		uint prev = atomicAdd(g_TileArgs.Cheap.x, MOTIONBLUR_TILE_REPLICATE); 
		g_CheapTiles[prev / MOTIONBLUR_TILE_REPLICATE] = tile;
		imageStore(g_NeighborHoodMax, pixelCoords, vec4(maxVelocity, 0.f, 0.f));
	}
	else
	{
		uint prev = atomicAdd(g_TileArgs.Expensive.x, MOTIONBLUR_TILE_REPLICATE); 
		g_ExpensiveTiles[prev / MOTIONBLUR_TILE_REPLICATE] = tile;
		imageStore(g_NeighborHoodMax, pixelCoords, vec4(maxVelocity, 0.f, 0.f));
	}
}
