#include "motion_blur/common.h"

layout(binding = 0, rg16f) uniform readonly image2D g_TileMin_Hor;
layout(binding = 1, rg16f) uniform writeonly image2D g_TileMin;
layout(binding = 2, rg16f) uniform readonly image2D g_TileMax_Hor;
layout(binding = 3, rg16f) uniform writeonly image2D g_TileMax;

layout(local_size_x = GROUP_SIZE, local_size_y = GROUP_SIZE) in;

void main()
{
    const ivec2 pixelCoords = ivec2(gl_GlobalInvocationID);
    if (pixelCoords.x >= g_PassSize.x || pixelCoords.y >= g_PassSize.y)
        return;

	const ivec2 tileUpperleft = ivec2(pixelCoords.x, pixelCoords.y * MOTIONBLUR_TILESIZE);

	float minMagnitudeSquared = FLT_MAX;
	vec2 minVelocity = vec2(FLT_MAX);

	float maxMagnitudeSquared = 0;
	vec2 maxVelocity = vec2(0);

	for (uint i = 0; i < MOTIONBLUR_TILESIZE; ++i)
	{
		const ivec2 pixel = ivec2(tileUpperleft.x, tileUpperleft.y + i);
		if (pixel.x >= 0 && pixel.y >= 0 && pixel.x < g_Size.x && pixel.y < g_Size.y)
		{
			vec2 velocity = imageLoad(g_TileMin_Hor, pixel).xy;
			float magnitudeSquared = dot(velocity, velocity);
			if (minMagnitudeSquared > magnitudeSquared)
			{
				minVelocity = velocity;
                minMagnitudeSquared = magnitudeSquared;
			}

			velocity = imageLoad(g_TileMax_Hor, pixel).xy;
			magnitudeSquared = dot(velocity, velocity);
            if(maxMagnitudeSquared < magnitudeSquared)
            {
                maxVelocity = velocity;
                maxMagnitudeSquared = magnitudeSquared;
            }
		}
	}

	imageStore(g_TileMin, pixelCoords, vec4(minVelocity, 0.f, 0.f));
	imageStore(g_TileMax, pixelCoords, vec4(maxVelocity, 0.f, 0.f));
}
