#include "motion_blur/common.h"

layout(binding = 0) uniform sampler2D g_Motion;
layout(binding = 1, rg16f) uniform writeonly image2D g_TileMin;
layout(binding = 2, rg16f) uniform writeonly image2D g_TileMax;

layout(local_size_x = GROUP_SIZE, local_size_y = GROUP_SIZE) in;

void main()
{
    const ivec2 pixelCoords = ivec2(gl_GlobalInvocationID);
    if (pixelCoords.x >= g_PassSize.x || pixelCoords.y >= g_PassSize.y)
        return;

	const uvec2 tileUpperleft = uvec2(pixelCoords.x * MOTIONBLUR_TILESIZE, pixelCoords.y);

	float minMagnitudeSquared = FLT_MAX;
	vec2 minVelocity = vec2(FLT_MAX);

	float maxMagnitudeSquared = 0;
	vec2 maxVelocity = vec2(0);

	for (uint i = 0; i < MOTIONBLUR_TILESIZE; ++i)
	{
		const uvec2 pixel = uvec2(tileUpperleft.x + i, tileUpperleft.y);
		if (pixel.x >= 0 && pixel.y >= 0 && pixel.x < g_Size.x && pixel.y < g_Size.y)
		{
			const vec2 uv = (pixel + 0.5) * g_TexelSize;
			const vec2 velocity = texture(g_Motion, uv).xy * g_Strength;

			const float magnitudeSquared = dot(velocity, velocity);
			if (minMagnitudeSquared > magnitudeSquared)
			{
				minVelocity = velocity;
                minMagnitudeSquared = magnitudeSquared;
			}
            if(maxMagnitudeSquared < magnitudeSquared)
            {
                maxVelocity = velocity;
                maxMagnitudeSquared = magnitudeSquared;
            }
		}
	}

	imageStore(g_TileMin, pixelCoords, vec4(minVelocity, 0.f, 0.f));
	imageStore(g_TileMax, pixelCoords, vec4(maxVelocity, 0.f, 0.f));
}
