#include "defines.h"

layout(binding = 0) uniform sampler2D g_AO;
layout(binding = 1) uniform sampler2D g_Edges;
layout(binding = 2) uniform sampler2D g_Depth;
layout(binding = 3, r8) uniform writeonly image2D g_Result;
#ifdef XE_GTAO_COMPUTE_BENT_NORMALS
layout(binding = 4) uniform usampler2D g_BentNormals;
layout(binding = 5, r32ui) uniform writeonly uimage2D g_ResultBentNormals;
#endif

#define XE_GTAO_DENOISE
#include "XeGTAO/XeGTAO.h"

layout(push_constant) uniform PushConstants
{
    GTAOConstants g_GTAO;
};

#define GROUP_SIZE 8
layout (local_size_x = GROUP_SIZE, local_size_y = GROUP_SIZE, local_size_z = 1) in;

void main(void)
{
	const ivec2 pixelCoords = ivec2(gl_GlobalInvocationID);
	if (pixelCoords.x >= g_GTAO.ViewportSize.x || pixelCoords.y >= g_GTAO.ViewportSize.y)
		return;

	const ivec2 pixCoordBase = pixelCoords * ivec2( 2, 1 ); // we're computing 2 horizontal pixels at a time (performance optimization)
    XeGTAO_Denoise(pixCoordBase, g_GTAO);
}
