#include "defines.h"
#include "XeGTAO/XeGTAO.h"

layout(binding = 0) uniform sampler2D g_AO;
layout(binding = 1) uniform sampler2D g_Edges;
layout(binding = 2, r8) uniform writeonly image2D g_Result;

layout(push_constant) uniform PushConstants
{
    ivec2 g_Size;
};

#define GROUP_SIZE 8
layout(local_size_x = GROUP_SIZE, local_size_y = GROUP_SIZE) in;

void main()
{
    const ivec2 pixelCoords = ivec2(gl_GlobalInvocationID);
    if (pixelCoords.x >= g_Size.x || pixelCoords.y >= g_Size.y)
        return;

	const vec2 texelSize = 1 / vec2(g_Size);
    const vec2 uv = (pixelCoords + 0.5) * texelSize;

	const vec4 edgesLRTB = XeGTAO_UnpackEdges(texelFetch(g_Edges, pixelCoords / 2, 0).x);

    // calculate index in the four deinterleaved source array texture
	const float fmx = float(pixelCoords.x % 2);
	const float fmy = float(pixelCoords.y % 2);

	// in case of an edge, push sampling offsets away from the edge (towards pixel center)
	const float fmxe = (edgesLRTB.y - edgesLRTB.x);
	const float fmye = (edgesLRTB.w - edgesLRTB.z);

	// calculate final sampling offsets and sample using bilinear filter
	const vec2 uvHorizontal = (vec2(pixelCoords) + 0.5 + vec2(fmx + fmxe - 0.5, 0.5 - fmy)) * texelSize;
	const float aoHorizontal = texture(g_AO, uvHorizontal).x;

	const vec2 uvVertical = (vec2(pixelCoords) + 0.5 + vec2(0.5 - fmx, fmy - 0.5 + fmye)) * texelSize;
	const float aoVertical = texture(g_AO, uvVertical).x;

	const vec2 uvDiagonal = (vec2(pixelCoords) + 0.5 + vec2(fmx - 0.5 + fmxe, fmy - 0.5 + fmye)) * texelSize;
	const float aoDiagonal = texture(g_AO, uvDiagonal).x;

	// reduce weight for samples near edge - if the edge is on both sides, weight goes to 0
	vec4 blendWeights;
	blendWeights.x = 1.0;
	blendWeights.y = (edgesLRTB.x + edgesLRTB.y) * 0.5;
	blendWeights.z = (edgesLRTB.z + edgesLRTB.w) * 0.5;
	blendWeights.w = (blendWeights.y + blendWeights.z) * 0.5;

	// calculate weighted average
	float blendWeightsSum = dot(blendWeights, vec4(1.0, 1.0, 1.0, 1.0));

	float ao = texelFetch(g_AO, pixelCoords / 2, 0).x;
	ao = dot(vec4(ao, aoHorizontal, aoVertical, aoDiagonal), blendWeights) / blendWeightsSum;

	imageStore(g_Result, pixelCoords, vec4(vec3(ao), 1));
}
